
networks:
  phpvibe-network:
    driver: bridge

services:
    phpvibe: 
        image: php:8.4-fpm-alpine
        working_dir: /var/www/
        restart: always
        user: 1000:1000
        volumes:
            - ./configs/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www
        networks:
            - phpvibe-network

    ngnix:
        image: nginx:alpine
        restart: always
        ports: 
            - "8080:8080"
        volumes:
            - ./configs/nginx:/etc/nginx/conf.d
            - ./:/var/www
        depends_on:
            - phpvibe
        networks :
            - phpvibe-network